name: SOLR Cloud

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Starting SOLR
        run: docker-compose -f docker/sas-solr-cloud/docker-compose.yml --project-directory . up -d 

      - name: Wait for SOLR to start
        run:  docker exec -t solr1 /opt/docker-solr/scripts/wait-for-solr.sh --max-attempts 10 --wait-seconds 5 --solr-url http://0.0.0.0:8983/

      - name: Selecting SOLR config
        run: export "config=solr.properties"

        # Due to the way docker-compose and SOLR works we can't access the SOLR cloud
        # from this machine. Instead we have to run the test within the cluster
      - name: Run Tests
        run: docker exec --workdir /usr/src/sas simpleannotationserver_web_1 /usr/bin/mvn -q test
